"""add allocation_transaction_id in cheques

Revision ID: dd8b5ef43555
Revises: 4c16c23ac734
Create Date: 2024-10-25 22:28:23.565974

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'dd8b5ef43555'
down_revision: Union[str, None] = '4c16c23ac734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cheques', sa.Column('allocation_transaction_id', sa.UUID(), nullable=False))
    op.create_foreign_key("allocation_transaction_id_constraint", 'cheques', 'transactions', ['allocation_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("allocation_transaction_id_constraint", 'cheques', type_='foreignkey')
    op.drop_column('cheques', 'allocation_transaction_id')
    # ### end Alembic commands ###
