"""add enum type in table custom_client_tokens

Revision ID: fa027b595775
Revises: f951261ffba9
Create Date: 2024-09-10 15:50:59.095885

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa027b595775'
down_revision: Union[str, None] = 'f951261ffba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

custom_enum_type = postgresql.ENUM('PROJECT', 'PRIVATE', name='customclienttokentype')


def upgrade() -> None:
    custom_enum_type.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_client_tokens', sa.Column('type', custom_enum_type, nullable=False, server_default='PROJECT'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_client_tokens', 'type')
    # ### end Alembic commands ###
