"""migrate currency type to numeric

Revision ID: 4c16c23ac734
Revises: b11f94f71d55
Create Date: 2024-10-23 15:43:51.023909

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4c16c23ac734'
down_revision: Union[str, None] = 'b11f94f71d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'amount',
                    existing_type=sa.BIGINT(),
                    type_=sa.Numeric(precision=20, scale=8),
                    existing_nullable=False)
    op.alter_column('transactions', 'destination_balance_before',
                    existing_type=sa.BIGINT(),
                    type_=sa.Numeric(precision=20, scale=8),
                    existing_nullable=False)
    op.alter_column('transactions', 'destination_balance_after',
                    existing_type=sa.BIGINT(),
                    type_=sa.Numeric(precision=20, scale=8),
                    existing_nullable=False)
    op.alter_column('transactions', 'source_balance_before',
                    existing_type=sa.BIGINT(),
                    type_=sa.Numeric(precision=20, scale=8),
                    existing_nullable=False)
    op.alter_column('transactions', 'source_balance_after',
                    existing_type=sa.BIGINT(),
                    type_=sa.Numeric(precision=20, scale=8),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'source_balance_after',
                    existing_type=sa.Numeric(precision=20, scale=8),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('transactions', 'source_balance_before',
                    existing_type=sa.Numeric(precision=20, scale=8),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('transactions', 'destination_balance_after',
                    existing_type=sa.Numeric(precision=20, scale=8),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('transactions', 'destination_balance_before',
                    existing_type=sa.Numeric(precision=20, scale=8),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    op.alter_column('transactions', 'amount',
                    existing_type=sa.Numeric(precision=20, scale=8),
                    type_=sa.BIGINT(),
                    existing_nullable=False)
    # ### end Alembic commands ###
