"""add table user_activity_statistics

Revision ID: 99571d8e5430
Revises: cef8ae637aca
Create Date: 2024-09-02 16:49:14.356929

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99571d8e5430'
down_revision: Union[str, None] = 'cef8ae637aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_activity_statistics',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb('{}')"), nullable=False),
                    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'datetime', name='user_activity_statistics_pk')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('user_activity_statistics')
    # ### end Alembic commands ###
    pass
