"""remove is_bot_start_completed from user entity and add created_at in task_done history

Revision ID: b11f94f71d55
Revises: fa027b595775
Create Date: 2024-10-21 21:38:08.453052

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b11f94f71d55'
down_revision: Union[str, None] = 'fa027b595775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_done_history', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###
    op.alter_column('users', 'is_bot_start_completed',
                    new_column_name='removed__is_bot_start_completed')


def downgrade() -> None:
    pass
