"""add event bonuses tables

Revision ID: 71ebdf16831f
Revises: b11f94f71d55
Create Date: 2024-10-29 01:35:08.433239

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM as PGEnum

# revision identifiers, used by Alembic.
revision: str = '71ebdf16831f'
down_revision: Union[str, None] = '4c16c23ac734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_bonuses',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('cooldown', sa.String(length=50), nullable=False),
                    sa.Column('conversion_to', PGEnum('GMEME', 'BMEME', name='currencytype', create_type=False), nullable=False),
                    sa.Column('min_win', sa.BigInteger(), nullable=False),
                    sa.Column('max_win', sa.BigInteger(), nullable=False),
                    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('event_bonus_activations',
                    sa.Column('user_id', sa.BigInteger(), nullable=False),
                    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('amount', sa.BigInteger(), nullable=False),
                    sa.Column('event_bonus_id', sa.BigInteger(), nullable=False),
                    sa.ForeignKeyConstraint(['event_bonus_id'], ['event_bonuses.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
                    sa.PrimaryKeyConstraint('user_id', 'datetime', name='event_bonus_activations_pk')
                    )
    op.create_index('ix_user_event_bonus', 'event_bonus_activations', ['user_id', 'event_bonus_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
