"""add filed api_configs in tasks

Revision ID: f951261ffba9
Revises: 1e93e6b81b71
Create Date: 2024-09-10 11:22:19.305573

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f951261ffba9'
down_revision: Union[str, None] = '1e93e6b81b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('api_configs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("jsonb('[]')"), nullable=False, comment='Stores API configurations for interactions with other projects'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('tasks', 'api_configs')
    # ### end Alembic commands ###
    pass
